 a. Read a matrix A from a csv file and a vector b from another csv file

In [5]:
import pandas as pd

# Creating matrix A
A = [[2, 1, 1], [1, 3, 2], [1, 2, 4]]

# Creating vector b
b = [1, 2, 3]

# Saving matrix A to csv file
pd.DataFrame(A).to_csv("A.csv", header=False, index=False)

# Saving vector b to csv file
pd.DataFrame(b).to_csv("b.csv", header=False, index=False)

# Reading matrix A from csv file
A = pd.read_csv("A.csv", header=None)
A = A.values

# Reading vector b from csv file
b = pd.read_csv("b.csv", header=None)
b = b.values.reshape(-1,1)

print("Matrix A:")
print(A)

print("Vector b:")
print(b)



Matrix A:
[[2 1 1]
 [1 3 2]
 [1 2 4]]
Vector b:
[[1]
 [2]
 [3]]


 b. Perform LU decomposition for square matrix

In [6]:
from scipy.linalg import lu

# Performing LU decomposition
P, L, U = lu(A)

print("Permutation Matrix P:")
print(P)

print("Lower Triangular Matrix L:")
print(L)

print("Upper Triangular Matrix U:")
print(U)

print("Decomposition A = P*L*U:")
print(P @ L @ U)


Permutation Matrix P:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Lower Triangular Matrix L:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.6 1. ]]
Upper Triangular Matrix U:
[[2.  1.  1. ]
 [0.  2.5 1.5]
 [0.  0.  2.6]]
Decomposition A = P*L*U:
[[2. 1. 1.]
 [1. 3. 2.]
 [1. 2. 4.]]


c.  Solve the equation Ax=b and check whether there are 0,1 or infinitely many solutions

In [8]:
import numpy as np

# Solving for x
x = np.linalg.inv(A) @ b

# Check if the solution is unique or not
rank_A = np.linalg.matrix_rank(A)
rank_AB = np.linalg.matrix_rank(np.hstack((A,b)))

if rank_A == rank_AB and rank_A == A.shape[1]:
    print("Unique solution. x = ")
    print(x)
elif rank_A == rank_AB and rank_A < A.shape[1]:
    print("Infinitely many solutions.")
else:
    print("No solution.")


Unique solution. x = 
[[0.07692308]
 [0.23076923]
 [0.61538462]]


 d.  Do the diagonalization of a matrix (assume it is symmetric)

In [15]:
from numpy.linalg import eig

# Find the eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = eig(A)

# Make sure that the matrix is symmetric
if (A.T != A).any():
    print("Matrix is not symmetric.")
else:
    # Diagonalize the matrix A
    D = np.diag(eigenvalues)
    P = eigenvectors

    print("Diagonalized Matrix D:")
    print(D)

    print("Eigenvectors Matrix P:")
    print(P)

    print("Diagonalization A = PDP^(-1):")
    print(P @ D @ inv(P))



Diagonalized Matrix D:
[[6.04891734 0.         0.        ]
 [0.         1.64310413 0.        ]
 [0.         0.         1.30797853]]
Eigenvectors Matrix P:
[[-0.32798528 -0.73697623  0.59100905]
 [-0.59100905 -0.32798528 -0.73697623]
 [-0.73697623  0.59100905  0.32798528]]
Diagonalization A = PDP^(-1):
[[2. 1. 1.]
 [1. 3. 2.]
 [1. 2. 4.]]


e.  Give exponential, sine and sigmoid functions on A

In [11]:
import numpy as np

# Applying exponential function on A
exp_A = np.exp(A)
print("Exponential of A:")
print(exp_A)

# Applying sine function on A
sin_A = np.sin(A)
print("Sine of A:")
print(sin_A)

# Applying sigmoid function on A
sig_A = 1 / (1 + np.exp(-A))
print("Sigmoid of A:")
print(sig_A)


Exponential of A:
[[ 7.3890561   2.71828183  2.71828183]
 [ 2.71828183 20.08553692  7.3890561 ]
 [ 2.71828183  7.3890561  54.59815003]]
Sine of A:
[[ 0.90929743  0.84147098  0.84147098]
 [ 0.84147098  0.14112001  0.90929743]
 [ 0.84147098  0.90929743 -0.7568025 ]]
Sigmoid of A:
[[0.88079708 0.73105858 0.73105858]
 [0.73105858 0.95257413 0.88079708]
 [0.73105858 0.88079708 0.98201379]]


f.   Find all the eigenpairs of A

In [12]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[6.04891734 1.64310413 1.30797853]
Eigenvectors:
[[-0.32798528 -0.73697623  0.59100905]
 [-0.59100905 -0.32798528 -0.73697623]
 [-0.73697623  0.59100905  0.32798528]]
